plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("com.google.devtools.ksp")
    // Firebase plugins - must be AFTER other plugins
    id("com.google.firebase.crashlytics")
    id("com.google.gms.google-services")  // MUST BE LAST
}

android {
    namespace = "com.plainlabs.qrpdftools"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.plainlabs.qrpdftools"
        minSdk = 26
        targetSdk = 34  // Target Android 14, but works up to Android 16
        versionCode = 2
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        
        // Vector drawables support for older Android versions
        vectorDrawables.useSupportLibrary = true
        
        // Resource optimization: Only keep English resources
        resourceConfigurations.add("en")
        
        multiDexEnabled = true
    }

    // Advanced Optimization: ABI Splits
    // Advanced Optimization: ABI Splits (Reverted per user request for single APK)
    // splits { ... }


    signingConfigs {
        // Debug signing (auto-generated by Android)
        getByName("debug") {
            // Uses default Android debug keystore
            // Located at: ~/.android/debug.keystore
        }
        
        // Release signing - using debug keystore for now
        // TODO: Replace with production keystore before publishing to Play Store
        create("release") {
            // For now, use debug keystore so release builds can install
            // Before production: Replace with your production keystore
            storeFile = file(System.getProperty("user.home") + "/.android/debug.keystore")
            storePassword = "android"
            keyAlias = "androiddebugkey"
            keyPassword = "android"
            
            // Enable all signature versions for maximum compatibility
            enableV1Signing = true  // JAR signing (Android 7.0 and below)
            enableV2Signing = true  // APK Signature Scheme v2 (Android 7.0+)
            enableV3Signing = true  // APK Signature Scheme v3 (Android 9.0+)
            enableV4Signing = true  // APK Signature Scheme v4 (Android 11.0+)
        }
    }

    buildTypes {
        // Debug uses default Android debug signing (works out of the box)
        debug {
            signingConfig = signingConfigs.getByName("debug")
            isMinifyEnabled = false
            isShrinkResources = false
            isDebuggable = true
        }
        
        release {
            signingConfig = signingConfigs.getByName("release")
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    
    compileOptions {
        isCoreLibraryDesugaringEnabled = true
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    
    kotlinOptions {
        jvmTarget = "17"
    }
    
    buildFeatures {
        viewBinding = true
    }
}

dependencies {
    // Core Android
    implementation("androidx.core:core-ktx:1.12.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.11.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    implementation("androidx.recyclerview:recyclerview:1.3.2")
    implementation("com.google.guava:guava:31.1-android")
    
    // Lifecycle & ViewModel
    implementation("androidx.lifecycle:lifecycle-viewmodel-ktx:2.7.0")
    implementation("androidx.lifecycle:lifecycle-livedata-ktx:2.7.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.7.0")
    implementation("androidx.activity:activity-ktx:1.8.2")
    implementation("androidx.fragment:fragment-ktx:1.6.2")
    
    // CameraX
    val cameraxVersion = "1.3.1"
    implementation("androidx.camera:camera-core:$cameraxVersion")
    implementation("androidx.camera:camera-camera2:$cameraxVersion")
    implementation("androidx.camera:camera-lifecycle:$cameraxVersion")
    implementation("androidx.camera:camera-view:$cameraxVersion")
    
    
    // ═══════════════════════════════════════════════════════════════════════════
    // ML KIT - FULLY BUNDLED (NO RUNTIME DOWNLOADS REQUIRED)
    // ═══════════════════════════════════════════════════════════════════════════
    // These are "BUNDLED" ML Kit libraries - all AI models are compiled directly
    // into the APK. The app works 100% offline with NO additional downloads needed
    // after installation. The user does NOT need to install any packages.
    //
    // Bundled vs Unbundled:
    // - ✅ BUNDLED (what we use): Models included in APK (~5-10MB larger APK)
    // - ❌ UNBUNDLED: Models download at runtime (requires internet on first use)
    //
    // Package names confirm bundled versions:
    // - com.google.mlkit:barcode-scanning (BUNDLED)
    // - com.google.mlkit:text-recognition (BUNDLED)
    //
    // Alternative unbundled versions we DON'T use:
    // - com.google.android.gms:play-services-mlkit-barcode-scanning (UNBUNDLED)
    // - com.google.android.gms:play-services-mlkit-text-recognition (UNBUNDLED)
    // ═══════════════════════════════════════════════════════════════════════════
    
    implementation("com.google.mlkit:barcode-scanning:17.2.0")        // Bundled models
    implementation("com.google.mlkit:text-recognition:16.0.0")        // Bundled models
    
    // Room Database
    val roomVersion = "2.6.1"
    implementation("androidx.room:room-runtime:$roomVersion")
    implementation("androidx.room:room-ktx:$roomVersion")
    ksp("androidx.room:room-compiler:$roomVersion")
    
    // PDF Library - Using iTextG (open source fork)
    implementation("com.itextpdf:itext7-core:7.2.5")
    
    // PowerPoint Support
    // PowerPoint Support
    implementation("org.apache.poi:poi-ooxml:5.2.5") {
        exclude(group = "org.apache.logging.log4j")
    }
    
    // HTML Conversion
    implementation("com.itextpdf:html2pdf:4.0.5")
    
    // Image processing for PDF scanner
    implementation("com.github.bumptech.glide:glide:4.16.0")
    
    // AdMob
    implementation("com.google.android.gms:play-services-ads:22.6.0")
    
    // Google Play Billing
    implementation("com.android.billingclient:billing-ktx:6.1.0")
    
    // Coroutines
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.7.3")
    
    // DataStore (for preferences)
    implementation("androidx.datastore:datastore-preferences:1.0.0")

    // Navigation Component
    val navVersion = "2.7.6"
    implementation("androidx.navigation:navigation-fragment-ktx:$navVersion")
    implementation("androidx.navigation:navigation-ui-ktx:$navVersion")
    
    // Testing
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")
    
    // Core library desugaring for Java 8+ APIs
    coreLibraryDesugaring("com.android.tools:desugar_jdk_libs:2.0.4")
    
    // ═══════════════════════════════════════════════════════════════════════════
    // FIREBASE - Automatic Crash Reporting
    // ═══════════════════════════════════════════════════════════════════════════
    
    // Firebase BOM (Bill of Materials) for version management
    implementation(platform("com.google.firebase:firebase-bom:34.8.0"))
    
    // Firebase Crashlytics - Automatic crash reporting
    implementation("com.google.firebase:firebase-crashlytics-ktx")
    
    // Firebase Analytics - Required for Crashlytics
    implementation("com.google.firebase:firebase-analytics-ktx")
}
